package connect

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gosuda/gyemoim/internal/config"
	"github.com/gosuda/gyemoim/internal/siwc"
)

const (
	connectBodyLimit  = 4 << 10
	maxStateLen       = 512
	maxAuthCodeLen    = 2048
	maxClientIDLen    = 512
	maxErrorLen       = 128
	completionTimeout = 60 * time.Second
	claimTimeout      = 30 * time.Second
)

// errEnrollmentUnavailable reports that the in-memory code registry is full.
var errEnrollmentUnavailable = errors.New("too many pending enrollment codes")

// ErrNotSIWC reports that the provider cannot use Sign in with ChatGPT.
var ErrNotSIWC = errors.New("provider does not support Sign in with ChatGPT")

// Enrollment is the result of issuing a connect enrollment code.
type Enrollment struct {
	Code             string
	ExpiresAt        time.Time
	ExpiresInSeconds int
}

// Service owns the enrollment codes and drives the siwc flow on their behalf.
type Service struct {
	store *config.Store
	oauth *siwc.Manager
	codes *codeStore
}

// NewService creates the enrollment service. The OAuth manager must be the
// same one serving /auth/callback and the /api/ OAuth routes.
func NewService(store *config.Store, oauth *siwc.Manager) *Service {
	return &Service{store: store, oauth: oauth, codes: newCodeStore()}
}

// StartEnrollment issues a single-use enrollment code bound to the provider.
// It is called only from the session-gated management API. Any earlier
// unclaimed code for the same provider becomes invalid. A claimed code whose
// flow later fails is dead regardless of the outcome; the admin issues a new one.
func (s *Service) StartEnrollment(ctx context.Context, providerID string) (Enrollment, error) {
	providerRecord, err := s.store.GetProvider(ctx, providerID)
	if err != nil {
		return Enrollment{}, err
	}
	if providerRecord.Type != "openai" {
		return Enrollment{}, ErrNotSIWC
	}
	code, expiresAt, err := s.codes.issue(providerID, time.Now())
	if err != nil {
		return Enrollment{}, err
	}
	return Enrollment{
		Code:             code,
		ExpiresAt:        expiresAt,
		ExpiresInSeconds: int(time.Until(expiresAt) / time.Second),
	}, nil
}

// ServeClaim handles POST /connect/claim for the enrollment script. It is
// deliberately mounted OUTSIDE the session and CSRF guards (see main.go): the
// script is not a browser, and the single-use enrollment code is the capability.
// Every failure answers with the same generic JSON error, so the endpoint never
// reveals whether a code existed, expired, or was already used.
func (s *Service) ServeClaim(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		w.Header().Set("Allow", http.MethodPost)
		writeConnectError(w, http.StatusMethodNotAllowed)
		return
	}
	var input struct {
		Code         string `json:"code"`
		CallbackPort *int   `json:"callbackPort"`
	}
	if !decodeConnectJSON(w, r, &input) {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	code := strings.TrimSpace(input.Code)
	if code == "" || len(code) > maxCodeLen || input.CallbackPort == nil ||
		*input.CallbackPort < 1 || *input.CallbackPort > 65535 {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	providerID, ok := s.codes.claim(code, time.Now())
	if !ok {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	ctx, cancel := context.WithTimeout(r.Context(), claimTimeout)
	defer cancel()
	authorizationURL, err := s.oauth.StartWithCallbackPort(ctx, providerID, *input.CallbackPort)
	if err != nil {
		// The code stays consumed: a failed start is a dead code.
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	// The state is generated by this server's own buildAuthorizationURL, so it
	// is parsed back out of the URL to link the code to its pending flow.
	parsed, err := url.Parse(authorizationURL)
	if err != nil {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	state := parsed.Query().Get("state")
	if state == "" || !s.codes.recordState(code, state, time.Now()) {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	providerRecord, err := s.store.GetProvider(ctx, providerID)
	if err != nil {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	writeConnectJSON(w, http.StatusOK, struct {
		AuthorizationURL string `json:"authorizationUrl"`
		ProviderName     string `json:"providerName"`
	}{AuthorizationURL: authorizationURL, ProviderName: providerRecord.Name})
}

// ServeComplete handles POST /connect/complete for the enrollment script. It
// shares ServeClaim's guard exemption (see main.go and ServeClaim): the claimed
// enrollment code plus the single-use OAuth state are the capability. The
// enrollment code is consumed at claim time and stays consumed regardless of
// the completion outcome.
func (s *Service) ServeComplete(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		w.Header().Set("Allow", http.MethodPost)
		writeConnectError(w, http.StatusMethodNotAllowed)
		return
	}
	var input struct {
		Code              string  `json:"code"`
		State             string  `json:"state"`
		AuthorizationCode string  `json:"authorizationCode"`
		ClientID          *string `json:"clientID"`
		Error             *string `json:"error"`
	}
	if !decodeConnectJSON(w, r, &input) {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	code := strings.TrimSpace(input.Code)
	state := strings.TrimSpace(input.State)
	if code == "" || len(code) > maxCodeLen || state == "" || len(state) > maxStateLen ||
		len(input.AuthorizationCode) > maxAuthCodeLen ||
		(input.ClientID != nil && len(*input.ClientID) > maxClientIDLen) ||
		(input.Error != nil && len(*input.Error) > maxErrorLen) {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	recordedState, ok := s.codes.claimedState(code, time.Now())
	if !ok || subtle.ConstantTimeCompare([]byte(recordedState), []byte(state)) != 1 {
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	// The code is dead from here on, whatever the outcome is.
	defer s.codes.finish(code)

	clientID, clientIDPresent := "", false
	if input.ClientID != nil {
		clientID, clientIDPresent = *input.ClientID, true
	}
	// A forwarded provider error ("access_denied" or any other non-empty value)
	// is passed through; the completion path maps it to the status vocabulary.
	authorizationError := ""
	if input.Error != nil {
		authorizationError = strings.TrimSpace(*input.Error)
	}
	ctx, cancel := context.WithTimeout(r.Context(), completionTimeout)
	defer cancel()
	status, err := s.oauth.CompleteConnectFlow(ctx, recordedState, input.AuthorizationCode, clientID, clientIDPresent, authorizationError)
	if err != nil {
		// Unknown, expired, or already consumed flow state: the same generic
		// error as every other failure, with no distinguishing detail.
		writeConnectError(w, http.StatusBadRequest)
		return
	}
	writeConnectJSON(w, http.StatusOK, struct {
		Status string `json:"status"`
	}{Status: status})
}

func decodeConnectJSON(w http.ResponseWriter, r *http.Request, target any) bool {
	body := http.MaxBytesReader(w, r.Body, connectBodyLimit)
	decoder := json.NewDecoder(body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return false
	}
	var trailing any
	return errors.Is(decoder.Decode(&trailing), io.EOF)
}

func writeConnectJSON(w http.ResponseWriter, statusCode int, value any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(statusCode)
	_ = json.NewEncoder(w).Encode(value)
}

// writeConnectError always answers with the same generic body: callers cannot
// distinguish an unknown code from an expired one, an already-used one, or any
// other rejection.
func writeConnectError(w http.ResponseWriter, statusCode int) {
	writeConnectJSON(w, statusCode, struct {
		Error struct {
			Message string `json:"message"`
			Type    string `json:"type"`
			Code    string `json:"code"`
		} `json:"error"`
	}{Error: struct {
		Message string `json:"message"`
		Type    string `json:"type"`
		Code    string `json:"code"`
	}{Message: "the enrollment code is invalid, expired, or already used", Type: "invalid_request_error", Code: "invalid_enrollment_code"}})
}
